### PR TITLE
Removing illegal keyword cascade from dropping user

### PR DESCRIPTION
**Pull request by vitoravancini**

### CODE REVIEW

**Comment by winglot** [comment]
Hi, thanks for the contribution.
Could you provide an example terraform code where the `CASCADE` is causing problems? The queries are based on spec available in AWS docs https://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_DEFAULT_PRIVILEGES.html where the cascade is listed as valid.
With a reproducible example, I will be able to contact AWS support to discuss the potential problems.

**Comment by vitoravancini** [comment]
I just wrote the query in a sql client and I get 

`SQL Error [500310] [0LP01]: [Amazon](500310) Invalid operation: Cascade behavior is not supported.;`

Here is the screenshot:

image

and sorry for the PR without description, this was actually a mistake, it was supposed to be pointing to my fork. my bad.

**Comment by vitoravancini** [comment]
My cluster version is 1.0.34272

**Comment by winglot** [comment]
Hey @vitoravancini, as an update on the issue - I've got a confirmation from AWS support that they were able to reproduce the problem and will be looking deeper whether it is just a documentation error or something else. I will wait with actions on this PR until got more information from them.

**Comment by vitoravancini** [comment]
Allright, that makes sense. I'm using my for for now, it's working nicely for me. 

Thank you for your provider by the way

**Comment by winglot** [comment]
Hey @vitoravancini, I finally have an update from AWS. AWS Redshift recently released a Role-based Access Control(RBAC) feature, which simplifies the managing of security privileges with Amazon Redshift.
RBAC doesn't support the CASCADE parameter when modifying privileges by using REVOKE and ALTER DEFAULT PRIVILEGES.
It is now also removed from the documentation pages.

Since the CASCADE keyword is also used with groups I will create a new PR with all the necessary changes that will supersede this. Thank you for your contribution.

**Comment by winglot** [comment]
As noted, this has been superseded by #47.

**Pull request closed without merging**
